Replace return with exit. This is a standalone script.

diff --git a/check_dyndns b/check_dyndns
--- a/check_dyndns
+++ b/check_dyndns
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 IPADDR=`wget -q -O - checkip.dyndns.com | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
-if [ $? -ne 0 ]; then echo "DNS WARNING: cannot detect ip address!"; return 1; fi
+if [ $? -ne 0 ]; then echo "DNS WARNING: cannot detect ip address!"; exit 1; fi
 
 /usr/lib/nagios/plugins/check_dns -H futurama.mine.nu -s 8.8.8.8 -a $IPADDR
 
